// <auto-generated />
using System;
using GameplayTimeTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameplayTimeTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GameplayTimeTracker.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastPlaytimeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPlaytimeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastPlaytimeId")
                        .IsUnique();

                    b.HasIndex("TotalPlaytimeId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameplayTimeTracker.Models.Playtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastTotalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Playtimes");
                });

            modelBuilder.Entity("GameplayTimeTracker.Models.PlaytimeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlaytimeHistories");
                });

            modelBuilder.Entity("GameplayTimeTracker.Models.RemoteMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HostOs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaveFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RemoteMachines");
                });

            modelBuilder.Entity("GameplayTimeTracker.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackupOnExit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("DpType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreferSGDBImages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("QuickAdd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemoteMachineId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RemoteSavingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SGDBApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SavingFreq")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartMinimized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartWithSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RemoteMachineId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("GameplayTimeTracker.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CBackground")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CButton")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CButtonFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CButtonNegative")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CButtonNegativeFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CButtonPositive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CButtonPositiveFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CCard1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CCard2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CFooter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CFooterFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CProgressBar1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CProgressBar2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CRunningIndicator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CShadow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CTransparency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressBarGradOrient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("GameplayTimeTracker.Models.Game", b =>
                {
                    b.HasOne("GameplayTimeTracker.Models.Playtime", "LastPlaytime")
                        .WithOne()
                        .HasForeignKey("GameplayTimeTracker.Models.Game", "LastPlaytimeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameplayTimeTracker.Models.Playtime", "TotalPlaytime")
                        .WithOne()
                        .HasForeignKey("GameplayTimeTracker.Models.Game", "TotalPlaytimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastPlaytime");

                    b.Navigation("TotalPlaytime");
                });

            modelBuilder.Entity("GameplayTimeTracker.Models.Settings", b =>
                {
                    b.HasOne("GameplayTimeTracker.Models.RemoteMachine", null)
                        .WithMany()
                        .HasForeignKey("RemoteMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameplayTimeTracker.Models.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
