<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net7.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
<!--        <UseWindowsForms>true</UseWindowsForms>-->
        <AssemblyName>GameplayTimeTracker</AssemblyName>
        <AssemblyVersion>2.0.0</AssemblyVersion>
        <ApplicationIcon>Assets\GameplayTimeTracker.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IconExtractor" Version="1.0.1"/>
<!--        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">-->
<!--            <PrivateAssets>all</PrivateAssets>-->
<!--            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
<!--        </PackageReference>-->
        <PackageReference Include="NotifyIcon.Windows" Version="1.23.10209.11223"/>
        <PackageReference Include="Shellify" Version="0.4.0" />
        <PackageReference Include="System.Drawing.Common" Version="8.0.10"/>
        <PackageReference Include="Extended.Wpf.Toolkit" Version="4.6.1"/>
        <PackageReference Include="WindowsShortcutFactory" Version="1.2.0"/>
        <PackageReference Include="MonoMac.NetStandard" Version="0.0.4" ExcludeAssets="runtime" />
        <PackageReference Include="AtkSharp" Version="3.24.24.95" ExcludeAssets="runtime" />
        <PackageReference Include="CairoSharp" Version="3.24.24.95" ExcludeAssets="runtime" />
        <PackageReference Include="GdkSharp" Version="3.24.24.95" ExcludeAssets="runtime" />
        <PackageReference Include="GioSharp" Version="3.24.24.95" ExcludeAssets="runtime" />
        <PackageReference Include="GLibSharp" Version="3.24.24.95" ExcludeAssets="runtime" />
        <PackageReference Include="GtkSharp" Version="3.24.24.95" ExcludeAssets="runtime" />
        <PackageReference Include="PangoSharp" Version="3.24.24.95" ExcludeAssets="runtime" />
        <PackageReference Include="Xceed.Wpf.Themes.MaterialDesign" ExcludeAssets="runtime" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\GameplayTimeTracker.ico" />
      <Content Include="Assets\GameplayTimeTracker.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\cog.png" />
      <Content Include="Assets\cog.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\add.png" />
      <Content Include="Assets\add.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\edit.png" />
      <Content Include="Assets\edit.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\folder.png" />
      <Content Include="Assets\folder.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\remove.png" />
      <Content Include="Assets\remove.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\save.png" />
      <Content Include="Assets\save.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\DefaultHero.png" />
      <Content Include="Assets\DefaultHero.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="Assets\DefaultIcon.png" />
      <Content Include="Assets\DefaultIcon.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Page Update="MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

</Project>
